[package]

name = "schwartzian_transform"
version = "0.0.1"
authors = [ "Marc Seeger <marcseeger@gmx.de>", "Jonathan Teige <j.teige@fh-muenster.de>" ]

[[bin]]

name = "schwartzian_transform"

[dependencies]
rand = "0.3"